### ISSUE TITLE
Implement API: GET /planters/featured

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#100]
This api is for the planters listed on the top page:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/5744708/165200031-0e588bdb-e191-4c4d-8a6e-5eabddef1dd2.png">

Currently, please simply list 10 newest planters order by created_at desc

To implement an endpoint:

- Please write an e2e test to cover it.
- Please follow the guide in the 'readme' to follow our architecture on the server-side.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
Prease refer to GET /trees/featured

**Comment by MundhadHarsh** [comment]
I would like to work on this issue, can you assign it to me ?

**Comment by dadiorchen** [comment]
@MundhadHarsh we have finished this one, can find another to work on? for example: this one is valid: https://github.com/Greenstand/treetracker-query-api/issues/244 can you take anyone as long as it is open

**Comment by MundhadHarsh** [comment]
Okay I'll check the #244, thank you
