### ISSUE TITLE
support: Get /trees?planter_id=1&order_by=created_at&desc=true

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#106]
To support the front end issue: https://github.com/Greenstand/treetracker-web-map-client/issues/584

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by waynelao** [comment]
Hi, I would like to tackle this issue. Just a clarification: is it should be Get /trees/?planter_id=1&order_by=created_at&desc=true ?

**Comment by dadiorchen** [comment]
@Mohmn has solved this one, please take another.
