### ISSUE TITLE
Extend GET /planters/[id] to return planter location (country name)

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#107]
To return the planter country name, because for the time being, the planter didn't upload the GPS location, we have to infer the location by the tree they planted: fine one tree planted by the planter -> find the tree location -> find the country where the location is.

Because currently, we don't have crossing countries planter, so it should be fine this way.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dagmawig** [comment]
I will tackle this.
