### ISSUE TITLE
Extend GET /planters/[id] to return continent

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#108]
Similar to this: https://github.com/Greenstand/treetracker-query-api/issues/107 but return continent (Aisa, Africa)

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by harris2310** [comment]
Hello there, I could resolve this for you

**Comment by dadiorchen** [comment]
@harris2310 great! Assigned to you. 
Just let you know, some other guys is working on other issue that simaliar to this one. like: @dagmawig is working on this: #119

**Comment by harris2310** [comment]
Sure!

**Comment by MohammadRayanShah** [comment]
Please add me on slack ,my email id is rayanshah379@gmail.com

**Comment by waynelao** [comment]
Hi, I have reviewed the code and this issue has been solved
