### ISSUE TITLE
endpoint get wallet by id or name returns an error when passing wallet name as query param

### ISSUE THREAD

**Issue by Mohmn** [Greenstand/treetracker-query-api#125]
![Screenshot from 2022-06-14 00-54-17](https://user-images.githubusercontent.com/37132584/173431613-b0c2ab7e-74ed-487a-b789-2af787aeed98.png)

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
oh, insomnia, I heard that one, it's for free? We are using postman

**Comment by Mohmn** [comment]
> oh, insomnia, I heard that one, it's for free? We are using postman @Mohmn 

Yep it's for free @dadiorchen.
Oh, Will switch to postman for this project then.

**Comment by dadiorchen** [comment]
I don't think you have to do that, I'd like to try insomnia when got chance, postman is great, but you will face charging for money when you heavily using it.
