### ISSUE TITLE
filter country board by continent

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#137]
Clicking on the tag can not trigger the update of the countries (by filter by that tag)

![Image](https://user-images.githubusercontent.com/5744708/182060734-28ce3d81-e0d4-460b-8285-d231e4dfac9b.png)

**Comment by dadiorchen** [comment]
@dagmawig could you please check if this API works?

**Comment by ParisaTork** [comment]
Fab, thanks @dadiorchen :) it's parisa_tork@yahoo.co.uk

**Comment by dagmawig** [comment]
@dadiorchen  if you remember the country leaderboard SQL was commented out because it takes too long. Currently the function is just returning a placeholder object.

**Comment by dadiorchen** [comment]
Great, @dagmawig could you please restore the real SQL for us?

**Comment by dagmawig** [comment]
Okay but I believe the SQL returns just top ten countries around the world. It doesn't really filter by continent. Is your intention to get top ten countries for each continent?

**Comment by dadiorchen** [comment]
Yes, there should be a query paraemter to set it like: continent=asia/global/...

**Comment by dagmawig** [comment]
But that would mean every time the user changes the filter parameter the request has to go back to the server, which would cause it to take a longer time. It already takes too long for the global filter. Can we just fetch everything at once and switch between the different filters on the client side?

**Comment by dadiorchen** [comment]
no need dag, we will use this chance to prove tha viability of the next cache.
