### ISSUE TITLE
API: /species/leaderboard

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#138]
We need an API `GET /species/leaderboard` 

The possible request parameter:

* limit: the list length
* planter_id: filter by planter
* organization_id: filter by organization
* wallet_id: filter by wallet

The response:
{
  list: [{
    id: xxx,
    name: [species name],
    count: [count of trees tagged with this species]
  }]
}

**Comment by kothariroshni8** [comment]
I would like to work on this issue.

**Comment by dadiorchen** [comment]
@kothariroshni8 as you said, maybe we should just use API: GET /species?[filter] for this goal. let's close this one first.
