### ISSUE TITLE
API: return registration/created time for GET /planters/{id} endpoint

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#142]
We need to add `created_at` field in the GET /planters/{id} (and also the GET /planters (list) endpoint), we are missing this field is because this field is not directly in the `planter` column, we need to find/join it from another table, `planter_registration` or something similar.

**Comment by waynelao** [comment]
I will work on this issue!

**Comment by waynelao** [comment]
Should I add created_at field at both GET /planters/{id} and GET /planters endpoints?
