### ISSUE TITLE
API: GET /trees/featured is missing species_name

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#145]
This api: https://dev-k8s.treetracker.org/query/trees/featured
The tree individual should include the `species_name`, just like: 
https://dev-k8s.treetracker.org/query/trees/186735

**Comment by kothariroshni8** [comment]
I would like to work on this issue.

**Comment by dadiorchen** [comment]
@kothariroshni8 thank your for taking it! Yes, please make a try, if you have any question, please comment here

**Comment by kothariroshni8** [comment]
Hi @dadiorchen ,
While running e2e test, I am getting below error 
`Self signed certificate in certificate chain`
I have added below code in app.ts but still is not running.
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

**Comment by dadiorchen** [comment]
Join our Slack huddle, I can help you out
