### ISSUE TITLE
API: `GET /wallets`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#146]
We are missing this API `GET /wallets?[filter....]` return wallet list, please implement it, could refer to similar API like: `GET /planters`

**Comment by mayankbucha** [comment]
@dadiorchen can I work on this issue?

**Comment by dadiorchen** [comment]
@mayankbucha yes, please!

**Comment by dadiorchen** [comment]
Please let me know if you have any question
