### ISSUE TITLE
The GET /countries/leaderboard to use real SQL to query the db

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#148]
No we are using mock data.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by kothariroshni8** [comment]
I would like to work on this issue.

**Comment by dadiorchen** [comment]
@dagmawig what's the situation of this issue? Have you done this?

**Comment by dagmawig** [comment]
I believe issue #137 would take care of this.

**Comment by dadiorchen** [comment]
@kothariroshni8 this has been solved, I will close this one
