### ISSUE TITLE
This GET /tokens/{uuid} response is wrong

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#154]
This api: https://dev-k8s.treetracker.org/query/tokens/b1e2d4f9-1c02-444f-9ca9-8b4477ee55cb
Returns empty body. Please help to check what happened.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by kothariroshni8** [comment]
I would like to work on this issue.

**Comment by dadiorchen** [comment]
@kothariroshni8 you are our hero!

**Comment by kothariroshni8** [comment]
Looks like we are passing capture Id instead of Id. 

`{
    "id": "0b041a8e-9a72-44ea-8419-b70c3a22f1ee",
    "capture_id": "b1e2d4f9-1c02-444f-9ca9-8b4477ee55cb",
    "wallet_id": "eecdf253-05b6-419a-8425-416a3e5fc9a0",
    "transfer_pending": false,
    "transfer_pending_id": null,
    "created_at": "2021-02-19T03:53:29.172Z",
    "updated_at": "2021-02-19T03:53:29.172Z",
    "claim": false,
    "tree_id": 218614,
    "tree_image_url": "https://treetracker-dev.nyc3.digitaloceanspaces.com/2018.06.14.19.59.35_799c8537-bce9-4997-96ca-9a0401e06fa2_IMG_20180614_142639_-714535546.jpg",
    "tree_species_name": null
}`

if we call API with id then it is working
 https://dev-k8s.treetracker.org/query/tokens/0b041a8e-9a72-44ea-8419-b70c3a22f1ee

**Comment by dadiorchen** [comment]
You mean the id in my url is actually a capture_id? then the API should respond 404 rather than empty body, right?

**Comment by dadiorchen** [comment]
@kothariroshni8 yes, we should respond 404 in this case
