### ISSUE TITLE
The default country leaderboard is borken

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#155]
https://dev-k8s.treetracker.org/query/countries/leaderboard

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by mayankbucha** [comment]
@dadiorchen it seems like the router path is not getting matched for `/leaderboard/:region` and it is going to the `/:id` path. I have created new router only for `/leaderboard`.

**Comment by dadiorchen** [comment]
@dagmawig I remeber you told me this has been solved or this actually is not an valid issue?

**Comment by dagmawig** [comment]
@mayankbucha What exactly did you put in the url?

**Comment by mayankbucha** [comment]
@dagmawig, when there is region param added to the leaderboard route in the url such as `/countries/leaderboard/asia` it is giving the correct results, whereas if the url is `/countries/leaderboard` , it is automatically going to the `/:id` route as no matching route is found. 

So I added another route `/leaderboard` similar to the `/leaderboard/:region` route. It will only be activated when there isn't any region param in the url.

```
router.get(
  '/leaderboard/:region',
  handlerWrapper(async (req, res) => {
    Joi.assert(req.params.region, Joi.string().required());
    const repo = new CountryRepository(new Session());
    const exe = CountryModel.getLeaderBoard(repo);
    const result = await exe(req.params.region);
    res.send({
      countries: result,
    });
    res.end();
  }),
);

router.get(
  '/leaderboard',
  handlerWrapper(async (req, res) => {
    const repo = new CountryRepository(new Session());
    const exe = CountryModel.getLeaderBoard(repo);
    const result = await exe('');
    res.send({
      countries: result,
    });
    res.end();
  }),
);
   
```

**Comment by dagmawig** [comment]
Great that makes sense. Or you can use `global` as region to retrieve the global top countries. Any string other than the reserved continent strings is going to retrieve the global top countries.

**Comment by mayankbucha** [comment]
Yes @dagmawig that can also be done, so shall I change this to support `/:region` param as `global` ?

**Comment by dagmawig** [comment]
I will say leave it the way you have it so that if users forget to put anything after `/leaderboard` it would still pull up the global leaderboard which I believe should be the default result.
