### ISSUE TITLE
The GET /trees/{id} should return wallet_id and wallet_name

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#156]
The GET /trees/{id} endpoint should return wallet_id and wallet_name fields, by joining `wallet.token` on `wallet.token.capture_id` = `trees.uuid` and join `wallet.token` and `wallet.wallet` on `wallet.token.wallet_id` = `wallet.wallet.id` , so we can get the id and the name of the wallet 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by mayankbucha** [comment]
@dadiorchen I would like to work on this issue next.
