### ISSUE TITLE
The GET /species need to return `desc`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#157]
Currently, all the case of GET /species?[filter...] is not returning `desc`, check code here: https://github.com/Greenstand/treetracker-query-api/blob/f5ecc43f9cce2c76699712188d99a3e4de5d933c/server/infra/database/SpeciesRepository.ts

Now we need to make sure they all return `desc` (description) fields.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by kothariroshni8** [comment]
I would like to work on this issue

**Comment by dadiorchen** [comment]
@kothariroshni8 cool!
