### ISSUE TITLE
GET /transactions API need to return wallet logo_url

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#161]
So we can draw the image on the UI
https://dev-k8s.treetracker.org/query/transactions?token_id=6c85c551-ed63-456f-ba0f-8d632897f560

![Image](https://user-images.githubusercontent.com/5744708/185526015-d0ae8fcb-4651-49b1-8841-9df73299a943.png)

**Comment by mayankbucha** [comment]
@dadiorchen I would like to work on this issue next.

**Comment by dadiorchen** [comment]
@mayankbucha go ahead!
