### ISSUE TITLE
The id of the tree in this API is wrong

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#173]
For this api: https://dev-k8s.treetracker.org/query/trees?organization_id=178
in the response, all the id in the `trees` list is 178, which is wrong, it should be the trees id here, rather than the id of the organization, also, we should add another field: `organization_id` and put the id 178 here.

**Comment by mayankbucha** [comment]
@dadiorchen, should I add `organization_id` field with `/:id` route as `/:id?organization_id=org_id`. If the organization_id query is provied it will filter with the `organization_id`, otherwise it will only filter with the tree id.

**Comment by dadiorchen** [comment]
Yes, I think we should do it too, I mean add it to the GET /trees/{id} if that's you are talking about. 

Please note, open separate PR for these two, don't combine them in single PR

**Comment by jeremydthomas** [comment]
Hello @mayankbucha, the tree id's in https://dev-k8s.treetracker.org/query/trees?organization_id=178 are still all 178, not sure if I should open a new issue or not as this is the same issue.

**Comment by dadiorchen** [comment]
@jeremydthomas can you check this again, it is returning tree id I think?

**Comment by jeremydthomas** [comment]
Yes, it does now. Maybe I was looking too soon before. Ill get on this, thank you @dadiorchen @mayankbucha
