### ISSUE TITLE
Please avoid sensitive information returning to client

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#176]
Please go through all routes under /wallets to avoid sensitive information like: salt, password hash to return to client:
for example: 
https://dev-k8s.treetracker.org/query/wallets/eecdf253-05b6-419a-8425-416a3e5fc9a0

Please remove `salt` and `password` fields.

**Comment by mayankbucha** [comment]
I would like to work on this issue.
