### ISSUE TITLE
GET /organizations return wrong id

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#187]
https://prod-k8s.treetracker.org/query/organizations?planter_id=3988&limit=20&offset=0 is returning planter id rather then org id

**Comment by dadiorchen** [comment]
@mayankbucha do you remember this one? is this a new bug or a existing one?

**Comment by mayankbucha** [comment]
@dadiorchen I think it's similar to issue #173 (tree id in this case).
I will check it out.
