### ISSUE TITLE
https://prod-k8s.treetracker.org/query/countries/leaderboard/global take too long time

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#194]
https://prod-k8s.treetracker.org/query/countries/leaderboard/global take too long time to return, need to do some research or optimization.

**Comment by Mohmn** [comment]
assign this one to me

**Comment by dadiorchen** [comment]
@Mohmn do you have any clue for this? Is it possible to speed up this query?

**Comment by Mohmn** [comment]
@dadiorchen im still researching, everthing seems properly implemeneted
 dont know  why this query is taking this much time

**Comment by dadiorchen** [comment]
Did you use `explain` to do some analysis?

**Comment by Mohmn** [comment]
> Did you use `explain` to do some analysis?

Yes
