### ISSUE TITLE
Set up Kubernetes deployment and Github Action to deploy mock server to dev env 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#2]
Please check our scripts for the same purpose in other repos, like: https://github.com/Greenstand/treetracker-web-map-api/actions/workflows/treetracker-webmap-server-deploy-dev.yml 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by Siddhant-K-code** [comment]
I wanted to join Slack and wanted to become a member of Greensand as Frontend + DevOps Developer.

siddhantkhare2694@gmail[dot]com
