### ISSUE TITLE
Throw 404 if tree.active is false

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#234]
for this case: https://prod-k8s.treetracker.org/query/trees/766520
It should throw 404 can not find the tree, because although the tree exists, but the `active=false` 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by WeiyuSun** [comment]
I can take this. Can you assign this to me? thanks!
