### ISSUE TITLE
Make the server being able to watch file change

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#250]
Currently we are using this command to run the server when we developing locally
https://github.com/Greenstand/treetracker-query-api/blob/c522b2f5719bb541677fe3764c44283fc9a01670/package.json#L33

We want to watch the file change, and restart the server once a change is detected, just like the `nodemon` command, but for TS.

Here are some research I made:
https://stackoverflow.com/questions/37979489/how-to-watch-and-reload-ts-node-when-typescript-files-change

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by jeremydthomas** [comment]
Closing this as it was fixed at some other date, nodemon is currently in the dev script.
