### ISSUE TITLE
Create Github Action to run the e2e when new code added into main branch

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#26]
The workflow:

1. Pass the code review and merge the PR
2. Deploy the code to dev env
3. Run e2e test and report the result.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by QuaidBartolomei** [comment]
@dadiorchen  I fixed the test configuration so that it will run `dotenv` before testing. We just need a  `DATABASE_URL` secret added to the github workflow
