### ISSUE TITLE
Limit the maximum pagination to 100 for every list.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#290]
For example: https://prod-k8s.treetracker.org/query/trees?organization_id=193&limit=100, currently, we set it to about 1000, it is a burden in terms of performance for us.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by kunalznk** [comment]
can i work on this

**Comment by jeremydthomas** [comment]
> can i work on this

Yes, please

**Comment by kunalznk** [comment]
can you add me into slack kunalznk@gmail.com

**Comment by jeremydthomas** [comment]
> can you add me into slack kunalznk@gmail.com
> 

I sent you one, if you didn't get it, let me know @kunalznk
