### ISSUE TITLE
Duplicated items show up in the planter list

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#314]
To reproduce:
visit: https://prod-k8s.treetracker.org/query/planters?organization_id=1787
There are some planters that get the same `id`

This is the reason that cause the bug: https://github.com/Greenstand/treetracker-web-map-client/issues/1589

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by aayushgauba** [comment]
gauba.aayush@gmail.com

**Comment by aayushgauba** [comment]
Done please review my changes in tree tracker repo
