### ISSUE TITLE
`/species` endpoint to support filter by grower

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#315]
We need to support something like: `https://dev-k8s.treetracker.org/query/v2/species?grower_id=93a026d2-a511-404f-958c-a0a36892af0f&limit=20&offset=0` 
so for this filter, by providing `grower_id` we filter the species by the `grower_id` or `grower_account_id` in the table to get the result, previously we use `planter` table, but now we are migrating to `grower_account` table for this.

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by mayankbucha** [comment]
grower_id (grower_account table)-> all capture_id (capture table)-> -> species_id (capture) -> id (tree_species) -> name (tree_species)
@dadiorchen is this approach correct?

**Comment by dadiorchen** [comment]
@mayankbucha this is for the v2 version, so please implement it under `/v2/`
@Kpoke can you help me on this, the way to filter species by grower id, under the now domain.

**Comment by aayushgauba** [comment]
@dadiorchen I am taking on this issue because it seems a lot similar to what I did last week
