### ISSUE TITLE
`/organizations` endpoint to support filter by grower

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#316]
Similar to #315 we need to migrate from: `https://dev-k8s.treetracker.org/query/v2/organizations?planter_id=8461&limit=20&offset=0` to 
`https://dev-k8s.treetracker.org/query/v2/organizations?grower_id=93a026d2-a511-404f-958c-a0a36892af0f&limit=20&offset=0`
which means we need to change the table to join from `planter` to `treetracker.grower_planter`

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by aayushgauba** [comment]
@dadiorchen Please assign this to me. Thanks!
