### ISSUE TITLE
500 error in https://prod-k8s.treetracker.org/query/wallets/featured

### ISSUE THREAD

**Issue by aayushgauba** [Greenstand/treetracker-query-api#347]
This is what I get when I load this page
![image](https://github.com/Greenstand/treetracker-query-api/assets/55630226/446ef45d-45e5-4970-aed3-c096fdaf9b38)

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@Kpoke do you know this? I saw you have some work on the `about` column, but should we upgrade the database when we do the release?
