### ISSUE TITLE
Error in Grower Organization Issue V2

### ISSUE THREAD

**Issue by aayushgauba** [Greenstand/treetracker-query-api#350]
I was working on webmap api when I got a 500 error
Traced it down and turns out there is an error in treetracker-query-api
[https://dev-k8s.treetracker.org/query/v2/growers?organization_id=22b7e221-0929-420b-a399-f0f0a0368be2](https://dev-k8s.treetracker.org/query/v2/growers?organization_id=22b7e221-0929-420b-a399-f0f0a0368be2)
![image](https://github.com/Greenstand/treetracker-query-api/assets/55630226/fbb9779f-0588-48ed-9872-e15ac018a58f)

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
We did some change on wallet.wallet table, I don't know if it is relevant

**Comment by aayushgauba** [comment]
@dadiorchen I dont think so, because this only happened for filter by organization_id
