### ISSUE TITLE
/raw-captures incorrectly parsing organization_Id

### ISSUE THREAD

**Issue by APH1997** [Greenstand/treetracker-query-api#358]
While investigating [issue 1106](https://github.com/Greenstand/treetracker-admin-client/issues/1106) on the treetracker admin client, I found that any query including organization_id sends back a validation error.

I think Joi is throwing this error because the queryFormatter function does not parse the organization_id back into an array.
Route and function below:

<img width="743" alt="Screenshot 2023-09-20 at 2 07 10 PM" src="https://github.com/Greenstand/treetracker-query-api/assets/118479307/61132d68-057a-44d6-ad6e-d252106d58f3">

<img width="754" alt="Screenshot 2023-09-20 at 1 58 24 PM" src="https://github.com/Greenstand/treetracker-query-api/assets/118479307/70403534-d701-4019-9de8-5e32a691660f">

**Comment by dadiorchen** [comment]
I think this is a valid issue

**Comment by uCryNet** [comment]
I take it

**Comment by uCryNet** [comment]
PR: https://github.com/Greenstand/treetracker-query-api/pull/360
