### ISSUE TITLE
Should return 404 if trees doesn't exist

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#36]
https://dev-k8s.treetracker.org/query/trees/123 will return 500, we should return 404 with message: can not find ...

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by tranquanghuy0801** [comment]
Is this status 404 also applied for /countries route as well?
