### ISSUE TITLE
`organisation_id` cannot be read as an array

### ISSUE THREAD

**Issue by SuspenseFallback** [Greenstand/treetracker-query-api#362]
## What is the error?

<img width="376" alt="Screenshot 2023-10-19 at 11 33 20 AM" src="https://github.com/Greenstand/treetracker-query-api/assets/86506971/1b009fc6-aff5-41a5-929c-d5ca8160fb67">

From some pages in the admin panel, the `organisation_id` value is given as a list in the query parameters. However, this returns an error in the API.

List example:

<img width="281" alt="Screenshot 2023-10-18 at 11 33 36 AM" src="https://github.com/Greenstand/treetracker-query-api/assets/86506971/6c695ab5-b6cb-4c5e-8699-0872ad3144d6">
 
As query parameters:

<img width="339" alt="Screenshot 2023-10-18 at 11 34 20 AM" src="https://github.com/Greenstand/treetracker-query-api/assets/86506971/ac6834e1-aa59-4d19-ae2b-da12aa1abf33">

### Steps to reproduce

1. Open the admin panel
2. Sign in as admin
3. Go to growers page (or stakeholders page)

The output: Forever stuck on this screen:

<img width="1680" alt="Screenshot 2023-10-18 at 11 35 30 AM" src="https://github.com/Greenstand/treetracker-query-api/assets/86506971/ab57d9aa-f1f6-4b64-9b11-3c988073c8ce">

Issue in admin panel: https://github.com/Greenstand/treetracker-admin-client/issues/1120

**Comment by SuspenseFallback** [comment]
This error also occurs in other pages, but they can still load. These include:

Capture Matching, Captures, Earnings, Payments

**Comment by mahimnamehta** [comment]
@SuspenseFallback Can you tell me more about it because as I see here on my local machine, this issue is not reproducing anymore. If you still find it reproducible then please give me the details to do so. If not can we close this issue?

**Comment by SuspenseFallback** [comment]
Oh, this was from a while ago. Probably got fixed. I'll close it.
