### ISSUE TITLE
Create `stakeholder/{stakehoulder_it}` api

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#372]
Create this api/endpoint:

https://github.com/Greenstand/treetracker-query-api/blob/ebf9d2cf474fc5ed8479809d54140ce5f80e3170/docs/api/spec/query-api.yaml#L273-L284

Please write unit test for the `repository` and check the SQL to fetch data gets executed correctly.

An example: https://github.com/Greenstand/treetracker-query-api/blob/main/server/infra/database/TreeRepositoryV2.spec.ts

**Comment by XLPeng57** [comment]
Hi @dadiorchen, I'd like to work on this!
