### ISSUE TITLE
Run `unit` test in CI/github action

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#373]
Run unit test, this is an example: https://github.com/Greenstand/treetracker-query-api/blob/main/server/infra/database/TreeRepositoryV2.spec.ts run the unit test in CI, when raise new pull request

**Comment by khalatevarun** [comment]
just checked the code @dadiorchen the test workflow in github actions is already set which runs all tests including unit and integrations test when a new pull request is raised, is there anything else you are expecting?
