### ISSUE TITLE
/tree/featured support `order by created_at desc`

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#39]
Prerequisites #37 

Now we just simply list the approved tree here, we need to show the newest tree (by `orderBy`)

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dagmawig** [comment]
I'm working on this.
