### ISSUE TITLE
Make the type of this function works:

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#5]
Make the type of this function works:

This function is for convenience to simple copy/reuse function:
https://github.com/Greenstand/treetracker-query-api/blob/8f74afa1292e35e907ea3d69e152a9c26c06c514/server/infra/database/delegateRepository.ts#L1-L8

use it:
https://github.com/Greenstand/treetracker-query-api/blob/8f74afa1292e35e907ea3d69e152a9c26c06c514/server/models/Country.ts#L20-L21

The problem is after using this fn, we lost the type (function signature) , you can see where are some `any`, is there a way to solve this using Typescript? 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@QuaidBartolomei what do you think? it's possible?

**Comment by dadiorchen** [comment]
Or maybe there is some better way to implement this, just delegate the fn to the repository

**Comment by QuaidBartolomei** [comment]
@dadiorchen I think this might work

```ts
export function delegateRepository<Type>(methodName: string): (r: any) => any {
  return function (repo: Type) {
    return async function (...args) {
      const result = await repo[methodName](...args);
      return result;
    };
  };
}
```

```ts
delegateRepository<CountryRepository>('getById'),
```
