### ISSUE TITLE
the tree list API support: /trees?tag=[tag_name]

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-query-api#52]
Now we already have: /trees? 
We need to make it support the query parameter: tag=[tag_name], the tag name was set in the admin panel as shown in the picture below.

<img width="1440" alt="Screen Shot 2022-01-20 at 5 21 03 PM" src="https://user-images.githubusercontent.com/5744708/150311579-d4016e5e-07d9-4ae9-b382-e4b077fb1072.png">

There is a tag table to support this feature, please ask me on slack if you don't understand the data table structure. 

---

Some hints:

- Please read our readme for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
select * from trees join tag on tag.id = trees.tag_id

**Comment by Mohmn** [comment]
actually, I found this project pretty interesting I would like to join your slack community email(naqashmohmin1@gmail.com)
sorry for asking u for an invite here as I couldn't find any other place for asking slack invitation

**Comment by dadiorchen** [comment]
@Mohmn hottest welcome! :D you are doing it at the right place.
